### PR TITLE
Added modals

### PR DESCRIPTION
**Pull request by cskiwi**
Don't know if this fully works, but from my initial testing it does.

### CODE REVIEW

**Comment by webbiesdk** [comment]
Looking at the code, it seems reasonable. 
But do you have some kind of demo that shows how to use it? 
You don't have to put it in index.html, just a little example would be nice.

**Comment by cskiwi** [comment]
added the example usage in the code;

**Comment by brennancheung** [comment]
One of the problems I've had with modals in the past is when it closes it doesn't create / have its own scope.  Since the DOM element resides on the page and is not created and destroyed each time the controller and the $scope stay around.

A problematic use case would be:
1) Admin clicks the "Add new user" button to open a modal.
2) Admin fills out some values.
3) Admin submits the modal and the user is added.
4) Admin clicks "Add new user" to add another user.
5) The previous values are still there.

A possible work around is to have an `ng-click` on the button as well that calls some initialization code but it is an inconvenience.

The pattern used by the angular bootstrap ui (I forget the exact name of the library), is that you pass in a template and a scope.  The template is compiled and injected into the DOM and destroyed when the modal closes.  That way the controller inside the template starts fresh each time.

**Comment by webbiesdk** [comment]
Just merged it, and added an example in index.html

**Comment by federicojasson** [comment]
@brennancheung 
I've created a plunker that you may find helpful (inspired in ui.bootstrap's modal):
http://plnkr.co/edit/rZxtyBSbJua2IcgFWCHA?p=preview

It's a service and a directive, and lets you open modals programatically.
It accepts the following parameters:
- template
- templateUrl
- resolve
- controller
- controllerAs

When the modal is closed, the scope is automatically destroyed.

Surely it can be improved, so I leave it here for revision.

**Comment by LunarDevelopment** [comment]
@federicojasson :+1:

**Pull request merged**
