### PR TITLE
Added disable option to date picker directive

### PR DESCRIPTION
**Pull request by danymar24**
I'm working with this module, and i added the pickadate disable option to the directive, i hope it's useful to someone

### CODE REVIEW

**Comment by webbiesdk** [comment]
You dont just add the disable option, you add some undocumented ui.materialize.truncate module, and remove min and max on pickdate.

If you had just added the disable option, I could accept it, but with these changes, I can't.

**Comment by webbiesdk** [comment]
If make a new commit, such that the only change is the disable option. I can merge this.

**Comment by danymar24** [comment]
sorry man, i was using an old version, i have updated and commited it with
the disable version, about the truncate module, i have erased it, i will
document it and commit later, thanks

**Comment by webbiesdk** [comment]
I dont see the commit in this pull request, but i can see it on your fork. 

I will just make a pull-request myself from your fork, and merge that.

**Comment by webbiesdk** [comment]
Okay, your code is merged in the other pull-request.

**Pull request closed without merging**
