### PR TITLE
Add max and min to input date directive

### PR DESCRIPTION
**Pull request by JonathanGuo**
Added support for specifying max and min date to input-date directive.

The value of max and min could be any valid date string which is
acceptable by constructor of Date object.

### CODE REVIEW

**Comment by JonathanGuo** [comment]
If necessary I can update the documentation.

**Comment by webbiesdk** [comment]
It would be nice with some updated documentation. 

You can just as well put that in before i merge.

**Comment by JonathanGuo** [comment]
Hi @webbiesdk . I have just updated documentation and optimised some codes.
Cheers.

**Comment by webbiesdk** [comment]
Looking good.

**Comment by JonathanGuo** [comment]
Great.

**Pull request merged**
