### PR TITLE
Fixes materializecss issue 901 Select list dropdown scrollbar closes …

### PR DESCRIPTION
**Pull request by beneficialmedia**
…the dropdown in IE

### CODE REVIEW

**Comment by webbiesdk** [comment]
There is no issue 901, do you mean issue #157?

**Comment by beneficialmedia** [comment]
No, that's a separate issue. This is related to [an issue with materializecss](https://github.com/Dogfalo/materialize/issues/901).

**Comment by webbiesdk** [comment]
Ok. 

So we are fixing it in angular-materialize, because the folks over at MaterializeCSS isn't going to fix it anytime soon? 

In that case, the code should include a comment stating that the code isn't needed when Dogfalo/materialize#901 is fixed.

**Comment by beneficialmedia** [comment]
That's correct. It may be a while (if ever) that this issue is fixed on their end. At the moment they're relying on individual sites/apps to fix it themselves. I'll add the comment.

**Comment by webbiesdk** [comment]
Ok, I merged it, thinking that it would work, since people said so over at the Materialize issue. 

The problem is that it causes an issue with multiple-select, where the select closes when one has selected something (which is not supposed to happen when multiple things can be selected). 

So can you answer what the line `$('input.select-dropdown').trigger('close');` was doing? Because I cannot see the use for it. (For now i have disabled that part of it when "multiple" is used).

**Pull request merged**
