### PR TITLE
added chips, fixed uglify-js version and added bower_components to .gitignore

### PR DESCRIPTION
**Pull request by nathenapse**
uglify-js version ^3.1.0 is not found, after bower_components is being tracked in git and added [chips](http://materializecss.com/chips.html)

### CODE REVIEW

**Comment by webbiesdk** [comment]
It would be really nice to have the example usage added to the index.html file.

**Comment by nathenapse** [comment]
I've added the documentation.

**Comment by webbiesdk** [comment]
Nice, I tested it and it worked. 

Good work!

**Comment by nathenapse** [comment]
thanks!

**Pull request merged**
