### PR TITLE
BugFix#139 - Multi-select disappears when adding ng-model attribut. T…

### PR DESCRIPTION
**Pull request by dhaval85**
Multi select issue with ng-model has been fixed.

Thanks to https://github.com/SteveBunlon

### CODE REVIEW

**Comment by webbiesdk** [comment]
The problem is, as far as I remember, that if statement is there so the select updates when the model changes from the outside. 

This just removes that feature, a better solution would be to fix it somehow, without removing the existing feature. 

I will look at it at some point, but don't expect this to be merged right away.

**Comment by dhaval85** [comment]
@webbiesdk 

I see. I'll look into this. Looks like it's circular watch happening at the moment. Therefore after first selection in case of multiselect it freezes. 

Regards, 
Dhaval

**Comment by webbiesdk** [comment]
@dhaval85 

That sounds like a good explanation. If you find a good way to fix it, just push it to your master branch, and it will show up in this pull-request. 

(For future reference, it is a good idea to create a separate branch for each pull-request that you make)

**Comment by dhaval85** [comment]
@webbiesdk 

Hey buddy. Yeah it was basically a circular watch. I added a check to break it. I tested it as well. Please confirm and merge it. 

Regards, 
Dhaval

**Comment by webbiesdk** [comment]
There was still an infinite loop with ng-model, but that is fixed now.

**Comment by SteveBunlon** [comment]
Hi everyone, 

Did u test the new code with the select directive ? I tryed it and it still disappears when I click on an item. 

Thanks for the work anyway, its a very good librairy. 

Regards, 

BUNLON Steve.

**Comment by webbiesdk** [comment]
I did test it, and i just tested it again. 

It works fine for me. 

I just added an example usage of multiple select in the demo, you can see it here: http://krescruz.github.io/angular-materialize/#select (clear cache if multiple doesn't show up)

Let me know if that doesn't work

**Comment by SteveBunlon** [comment]
Well, I tryed it again.

I am using chrome. And even if I am in private navigation mode, the select still disepears when I choose/remove an item. Maybe keeping the select dropdown shown when we click an item is not your goal. Is it ?

I tryed with firefox to, and I have the same problem, and I asked a colleague to.

**Comment by webbiesdk** [comment]
("tryed" is actually spelled "tried")

Oh, now i see, we were talking about different issues. 

The Material-select was completely bugging out in some cases, and that is what was fixed here. 

So yeah, for now the dropdown closes when selecting something (although it shouldn't). 

(Note to self: read issues before closing them)

**Comment by SteveBunlon** [comment]
(sorry for the mistake,I am not english)

Well understood, should I create a new issue so ?

**Comment by webbiesdk** [comment]
No need, the "new" issue was covered by #139 (i just need to read). 

I just fixed it in the above commit, you can try it out at http://krescruz.github.io/angular-materialize/#select (clear cache if it doesn't work).

**Comment by SteveBunlon** [comment]
Pretty cool ! It is working fine now. 

Thanks for the work !

Best regards, 

BUNLON Steve.

**Comment by dhaval85** [comment]
Thank you guys. 

@webbiesdk when you gonna release new bower update?

**Comment by webbiesdk** [comment]
I just released 0.1.4, which bower should pick up. 

Gonna update npm as well.

**Comment by dhaval85** [comment]
Thanks man

**Pull request merged**
