### PR TITLE
Added the materializecss's tooltip feature

### PR DESCRIPTION
**Pull request by toben**
It was impossible to make a directive named "tooltip" because of ambiguous error into data-tooltip attribute and the directive. So I named it : "tooltipped".

### CODE REVIEW

**Comment by toben** [comment]
```
          <ul id='{{row.id}}' class='dropdown-content'>
            <li tooltipped data-delay="50" data-position="right" data-tooltip="Éditer"><a href="javascript:void(0);" class="center-align blue-text"><i class="mdi-content-create"></i></a></li>
            <li tooltipped data-delay="50" data-position="right" data-tooltip="Supprimer"><a href="javascript:void(0);" class="center-align red-text"><i class="mdi-action-delete"></i></a></li>
          </ul>
```

It's weird...my directive works only for the last li and I don't have a solution for that.

**Comment by webbiesdk** [comment]
That it only works on the last is a general problem, and I've found why. 

If you look at the following line: https://github.com/Dogfalo/materialize/blob/ce5e0ba9f0ac2e32e0f2d9f8859928af32c6b0dd/js/tooltip.js#L16

```
//Remove previously created html
$('.material-tooltip').remove();
```

When it initializes a new tooltip, it first removes all the previously created tooltips. 

The solution is to initialize all tooltips whenever the link function in the directive runs. Which I did in 242203d2acd821da01c00f242b13395fc9dcc9d6

**Comment by toben** [comment]
"The solution is to initialize all tooltips whenever the link function in the directive runs. "

I didn't want to do that because it's overkill. If you have a big table with a lots of tooltips (like I have), it will take a lots of ressources.

I fixed that for the moment directly into the materialize.js.
You can see my solution here :
https://github.com/Dogfalo/materialize/issues/1386

Now...we have to wait a fix from them....

**Comment by webbiesdk** [comment]
Okay, I helped them a bit Dogfalo/materialize#1547. 

If they update their code, then we can change the implementation here as well.

**Pull request merged**
