### PR TITLE
Modal options updated

### PR DESCRIPTION
**Pull request by iqqmuT**
- modal options are camelCase
- modal options `startingTop` and `endingTop` added

### CODE REVIEW

**Comment by iqqmuT** [comment]
Updated materialize to 0.98.1, changed options to camelCase.

**Comment by webbiesdk** [comment]
The string `0.97.8` appears many other places in the repository, what you have done is a very incomplete update to 0.98.1. 

Have you tested that the existing directives work with an update to 0.98.1? 

I know I might be picky, but an update of Materialize is all or nothing.

**Comment by iqqmuT** [comment]
It's good to be picky, it maintains the good quality. :)
`index.html` is now updated to use 0.98.1, are there other references to it? I tested with `index.html` and the directives work well.

**Comment by webbiesdk** [comment]
I think the only one missing is `bower.json`

**Comment by iqqmuT** [comment]
I already updated it: `"materialize": "~0.98.1",`

**Comment by webbiesdk** [comment]
Oh, missed it.

I'll do a merge first, test later (it's easier).

**Comment by webbiesdk** [comment]
Yep, it seems to be working fine.

**Pull request merged**
